version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_DB_URL: "mongodb://mongo:27017/"
      MONGO_DB_NAME: "candidate_database"
      SECRET_KEY: "your_secret_key"

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"


